[package]
name = "gpterminal-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai = "1.0.0-alpha.6"
termimad = "0.20"
dotenvy = "0.15.6"
tokio = { version = "1.26.0", features = ["full"] }
